"""empty message

Revision ID: 13d1b47ddf5a
Revises: 
Create Date: 2022-08-15 20:53:29.297501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d1b47ddf5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('work_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('access_notes', sa.String(length=100), nullable=True),
    sa.Column('entry_allowed', sa.Boolean(), nullable=False),
    sa.Column('bill_to_customer', sa.Boolean(), nullable=False),
    sa.Column('maintenance_notes', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_order')
    op.drop_table('user')
    # ### end Alembic commands ###
