"""empty message

Revision ID: 73769308ea86
Revises: 13d1b47ddf5a
Create Date: 2022-08-19 21:15:26.164744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73769308ea86'
down_revision = '13d1b47ddf5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workorder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('access_notes', sa.String(length=100), nullable=True),
    sa.Column('entry_allowed', sa.Boolean(), nullable=False),
    sa.Column('bill_to_customer', sa.Boolean(), nullable=False),
    sa.Column('maintenance_notes', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_workorder',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workorder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workorder_id'], ['workorder.id'], )
    )
    op.drop_table('work_order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('access_notes', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('entry_allowed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('bill_to_customer', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('maintenance_notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='work_order_pkey')
    )
    op.drop_table('user_workorder')
    op.drop_table('workorder')
    # ### end Alembic commands ###
